### ISSUE TITLE
lsusb_darwin issue

### ISSUE THREAD

**Issue by cedwardsmedia** [hephaest0s/usbkill#63]
Not exactly sure what's causing this. I'll be glad to provide more information if needbe. I double checked and everything in my config is valid.

```
sudo /usr/local/bin/python3 /Users/cedwardsmedia/Scripts/usbkill.py --no-shut-down
             _     _     _ _ _
            | |   | |   (_) | |
  _   _  ___| |__ | |  _ _| | |
 | | | |/___)  _ \| |_/ ) | | |
 | |_| |___ | |_) )  _ (| | | |
 |____/(___/|____/|_| \_)_|\_)_)

[NOTICE] Ready to execute all the (potentially destructive) commands, but NOT shut down the computer.
Traceback (most recent call last):
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 137, in check_inside
    result["Built-in_Device"]
KeyError: 'Built-in_Device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 379, in <module>
    loop(settings)
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 252, in loop
    start_devices = lsusb()
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 166, in lsusb
    return lsusb_darwin()
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 159, in lsusb_darwin
    check_inside(result, devices)
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 152, in check_inside
    check_inside(result_deep, devices)
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 152, in check_inside
    check_inside(result_deep, devices)
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 152, in check_inside
    check_inside(result_deep, devices)
  File "/Users/cedwardsmedia/Scripts/usbkill.py", line 144, in check_inside
    devices.append(DEVICE_RE[1].findall(result["vendor_id"])[0] + ':' + DEVICE_RE[1].findall(result["product_i$
IndexError: list index out of range
```

**Comment by hephaest0s** [comment]
Thanks for reporting! However, this issue is identical to issue #61
