### ISSUE TITLE
Error on executing usbkill.py on Qubes.

### ISSUE THREAD

**Issue by Lafachief** [hephaest0s/usbkill#98]
Traceback (most recent call last):
  File "usbkill.py", line 466, in <module>
    go()
  File "usbkill.py", line 463, in go
    loop(settings)
  File "usbkill.py", line 320, in loop
    start_devices = lsusb()
  File "usbkill.py", line 228, in lsusb
    return DeviceCountSet(DEVICE_RE[0].findall(subprocess.check_output("lsusb", shell=True).decode('utf-8').strip()))
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'lsusb' returned non-zero exit status 1

following error is displayed.

**Comment by adamthiede** [comment]
I had this same problem, since these two projects seem like a great pair.
The problem is Qubes' dom0 has no USB devices attached in a default set up - it all goes through the 'sys-usb' and there's no way to pass USB to dom0 (I think that's a security concern). One could implement a daemon in dom0 to watch a file or device in sys-usb. Otherwise, running this in one of qubes' VMs just shuts down the VM.
I might work on this if you're still interested.

**Comment by anonaddict** [comment]
Did anyone get it to work?

**Comment by adamthiede** [comment]
I've yet to try out the latest Qubes release but thanks for reminding me. It might work better since I believe it's based on a much newer OS.

**Comment by anonaddict** [comment]
I don't think the OS is the issue. The issue is very likely the way Qubes is built around virtualization and compartmentalization https://forum.qubes-os.org/t/yubikey-usbkill/10053
